homework-5
BBlack96/aqa-advanced pull request #6
Opened 2024-01-30 17:22 UTC by BBlack96

2024-01-30 20:55 UTC, sttaran requested changes

2024-01-30 20:55 UTC, sttaran commented on JSBasics/Homework-5/task-2.js
> +const isOld = (age) => age >= 18
`isAdult` would be better name :)

2024-01-30 20:55 UTC, sttaran commented on JSBasics/Homework-5/task-3.js
> +            break
we do not need break in default block, it is always last

2024-01-30 22:05 UTC, BBlack96 commented on JSBasics/Homework-5/task-2.js
> +const isOld = (age) => age >= 18
agree)

2024-01-30 22:06 UTC, BBlack96 commented on JSBasics/Homework-5/task-3.js
> +            break
sorry( my bad

2024-01-31 08:23 UTC, sttaran approved these changes

2024-01-31 08:25 UTC, merged